/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:c67a35d0-834f-4cbf-9782-64bb2faafa3a",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_YgSc5MgDd",
    "aws_user_pools_web_client_id": "3s3eerk065o4aga54d7jjphm1v",
    "oauth": {}
};


export default awsmobile;
